### ISSUE TITLE
Column not found: 1054 Unknown column 'oc.is_sent' in 'where clause' 

### ISSUE THREAD

**Issue by cdiacon** [dotmailer/dotmailer-magento2-extension#139]
The upgrade script for the versions lower then 2.0.5 will generate this : 

 SQLSTATE[42S22]: Column not found: 1054 Unknown column 'oc.is_sent' in 'where clause', query was: UPDATE `email_campaign` AS `nc`  
   LEFT JOIN `email_campaign` AS `oc` ON oc.id = nc.id                                                                               
  SET `nc`.`send_status` = 2                                                                                                         
  WHERE (oc.is_sent =1)

this update query has wrong logic in binding and then update fro the same table : 
```
//update table with historical send values
            $select = $connection->select();

            //join
            $select->joinLeft(
                ['oc' => $campaignTable],
                "oc.id = nc.id",
                [
                    'send_status' => new \Zend_Db_Expr(\Dotdigitalgroup\Email\Model\Campaign::SENT)
                ]
            )->where('oc.is_sent =?', 1);

            //update query from select
            $updateSql = $select->crossUpdateFromSelect(['nc' => $campaignTable]);
```

**Comment by adeelq** [comment]
@cdiacon login is fine. I'm creating a new column "send_status" before running this above query. And removing column "is_sent" after running the query. 

What above query is doing is filling new column "send_status" with value "2" if  column "is_sent" = 1

**Comment by cdiacon** [comment]
@adeelq : 

how to replicate : 

* set back the version to 2.0.5 
* update module
* run upgrade command


look careful at the left join
```
UPDATE email_campaign AS nc
LEFT JOIN email_campaign AS oc ON oc.id = nc.id
SET nc.send_status = 2
WHERE (oc.is_sent =1)
```

**Comment by adeelq** [comment]
@cdiacon if you "set back the version to 2.0.5" in that case "is_sent" does not exist anymore because it is removed. So the problem is if you on higher version where column "is_sent" does not exist anymore and then you go back to version 2.0.5 then it is gonna throw error because "is_sent" does not exist.

i think all should work fine if you are not going back to version. 

One way i can see so this does not throw error to check if "is_sent" column exist or not. if exist then run the query. Agree?

**Comment by cdiacon** [comment]
@adeelq A simple check for is_sent should work just fine.
