### ISSUE TITLE
Order sync duplicate email for guests

### ISSUE THREAD

**Issue by cdiacon** [dotmailer/dotmailer-magento2-extension#192]
Modified orders will create duplicate guest in email_contact table for the same websites.

**Comment by cdiacon** [comment]
@adeelq we don't task for this one, what was this about https://github.com/dotmailer/dotmailer-magento2-extension/commit/4856cc04dff5fba10bc3e115bea76c5f8a9fe443 ?

**Comment by adeelq** [comment]
@cdiacon As per this commit https://github.com/adeelq/dotmailer-magento2-extension/commit/915c40e8a59ad56d50b1d7449405a87e8194799c We will not find and create guest during order sync prcoess

However from above commit this code will create duplicates since we will getting all guest contacts that are not in contacts table. So there can be more then one guest order made by same guest contact. 

I'm closing this and will be doing commit in the original issue https://github.com/dotmailer/dotmailer-magento2-extension/issues/187
