### ISSUE TITLE
Use Monolog for logging as per Magento 2 guidelines

### ISSUE THREAD

**Issue by Alberts00** [dotmailer/dotmailer-magento2-extension#485]
Hello!
Currently the extension is using `\Zend\Log\Writer\Stream ` interface for logging which is causing issues since the logging format differs (time, class.level)  from the Magento 2 suggested `\Psr\Log\LoggerInterface`. In addition to this, it is also not possible to send logs to centralized logging server i.e Logstash from Monolog, because it is being completely bypassed.

It would be great if the logging was implemented as per Magento 2 [guidelines](http://devdocs.magento.com/guides/v2.2/config-guide/log/log-magento.html) by using `\Psr\Log\LoggerInterface`.

**Comment by simon-letch** [comment]
Hey @Alberts00,

I'm interested to hear more about your setup and how you're configuring Monolog to push to LogStash.

We're currently weighing up whether to inject Psr\Log\LoggerInterface everywhere we currently use logging and having all our logs go to the standard Magento log. Or creating a new logger implementation which extends Monolog, has a handler which outputs to our custom log file and inject that everywhere we currently use logging.

**Comment by jordanvector** [comment]
I am also very interested in this^

**Comment by scottsb** [comment]
Now that this is bundled with Magento core, it is extremely odd not to use Magento's standard logging mechanism. The reason there *is* a standard logging mechanism is so that logging can be centrally managed, and the reason it uses Monolog (as opposed to M1's proprietary implementation) is so that it can be plugged into a variety of output formats.

**Comment by sta1r** [comment]
Hi all, please consider the above proposed implementation for Monolog in our connector. 

We had two options:
1. Inject `\Psr\Log\LoggerInterface` and log to regular Magento logs
2. Extend Monolog and enable different types of logging to our existing separate connector.log

We decided on 2 because the regular logs can get very busy, and clients are already used to having a separate dotdigital log, which they can access via the admin. However we're open to community feedback!

**Comment by scottsb** [comment]
I like maintaining separate log file, though I left a comment over on the PR about a possible bug in this specific implementation (probably best to keep that conversation over there).

**Comment by sta1r** [comment]
We have now released our Monolog implementation in [v3.4.0](https://github.com/dotmailer/dotmailer-magento2-extension/releases/tag/v3.4.0). Thank you all for raising / contributing.
