### ISSUE TITLE
2.5.1 on Magento 2.2.3 freezing the checkout

### ISSUE THREAD

**Issue by bhagdave** [dotmailer/dotmailer-magento2-extension#510]
We have attempted to put the latest version into a Magento 2.2.3 site and it freezes when we complete the checkout.  The payment is taken, a transactional email is sent from Dotmailer but then it just stalls.  New Relic reports that the following /Webapi/Rest/Magento\Checkout\Api\GuestPaymentInformationManagementInterface/savePaymentInformationAndPlaceOrder is taking 250 seconds to respond..

**Comment by cdiacon** [comment]
@bhagdave 
can you provide more info, error in the logs for example? or if you can find anything useful inside the browser console?

Thanks,
Calin.

**Comment by cdiacon** [comment]
@bhagdave 
1. do you have any tracking plugin for your browser like uBlock?
2. do you have the tracking enabled  on the configuration page?

**Comment by simon-letch** [comment]
Hi @bhagdave,

I'm going to close this issue.

Calin is alluding to an issue Magento had which caused script load failures to block the checkout process. The fix for that happened in this pull request: https://github.com/magento/magento2/pull/14874

Magento stated that it was ported to 2.2.5 but I could only see it in 2.2.6.

Thanks,
Simon
