### ISSUE TITLE
Do you have 2.6.x releases?

### ISSUE THREAD

**Issue by andkirby** [dotmailer/dotmailer-magento2-extension#530]
Hi there,

I didn't find 2.6.x versions despite on I have in Magento 2.2.5:
```
$ composer show | grep dotma
dotmailer/dotmailer-magento2-extension               2.6.0
```

Actually, I got a bug in both 2.6.0 & 2.6.1.

So, what's the deal with 2.6.x?
Should I create an issue for a bug?

**Comment by simon-letch** [comment]
Hey,

We had some issues between releasing code to Magento and needing to release a patch version to our existing client base which meant we can't tag the 2.6.X versions in our github repository.

Please create the issue here and we'll address it accordingly. We maintain a single release branch so the fix will be part of our next appropriate release.

Thanks,
Simon

**Comment by simon-letch** [comment]
I'm going to close this issue.

**Comment by rafallmmw** [comment]
Hello,

is there any way to get 2.6.1 version?

regards
Rafal

**Comment by simon-letch** [comment]
Only from the Magento package repository.

We've got a process in place to stop this situation occurring in the future.
