### ISSUE TITLE
Cannot install module on magento 2.3.2 EE version

### ISSUE THREAD

**Issue by rafashkembi** [dotmailer/dotmailer-magento2-extension#553]
I tried installing the module on an enterprise magento 2.3.2 and it fails due to composer conflicts. 

![image](https://user-images.githubusercontent.com/41292729/65955898-73ea6f00-e449-11e9-9a56-5880a35bf080.png)

Thanks,
Rafael

**Comment by sta1r** [comment]
Hi there, please can you try:
```
composer require dotmailer/dotmailer-magento2-extension:"3.4.2 as 3.1.2"
```

**Comment by rafashkembi** [comment]
Hi @sta1r 

It worked.

![image](https://user-images.githubusercontent.com/41292729/65958225-31c42c00-e44f-11e9-9992-023b03bb5d64.png)

Will it be a new release for this issue or we need to use it like this?

**Comment by sta1r** [comment]
@rafashkembi This is a side-effect of Magento bundling, and the fact that our release cycles are more frequent than those of Magento core. We regularly advise merchants to use the above method to install a more recent version of our connector than was bundled with their current Magento version.

In your case, I'm guessing you were running Magento v2.3.1 (or lower) with v3.4.x of our connector. At upgrade to Magento v2.3.2, your installation threw an error because `dotmailer/dotmailer-magento2-extension` v3.1.2 is listed as a dependency in the composer.lock file for Magento Commerce 2.3.2, and your installed version was higher. 





It looks like you were previously running a more recent version of our extension than came bundled.
