### ISSUE TITLE
Error filtering template: Notice: Undefined variable: productViewEvent in /public_html/vendor/dotmailer/dotmailer-magento2-extension/Plugin/ReportsProductCollectionPlugin.php on line 60

### ISSUE THREAD

**Issue by engmonged** [dotmailer/dotmailer-magento2-extension#570]

**Comment by sta1r** [comment]
Hello @engmonged thanks for alerting us to this. We are going to remove this plugin from our module, since it was only designed to override part of the observed method in Magento 2.0. From Magento 2.1 onwards, our plugin code is identical to the observed `addViewsCount()` method. 

See: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Reports/Model/ResourceModel/Product/Collection.php#L332-L368

If you are seeing the above error, it is likely that you will continue to see it even after we remove the plugin, because core code is the same.
