### ISSUE TITLE
Undefined property: stdClass::$status

### ISSUE THREAD

**Issue by dbashyal** [dotmailer/dotmailer-magento2-extension#587]
![image](https://user-images.githubusercontent.com/833986/182267246-267d3a0d-f654-4781-9738-33f01a4534cd.png)

**Comment by sta1r** [comment]
@dbashyal Thanks for this. If the Dotdigital API is functioning correctly you should always get a status in the response - see https://developer.dotdigital.com/reference/get-transactional-data-import-status. Do these errors persist or have they disappeared now? We will add an extra check for the `status` property in a future release.

**Comment by dbashyal** [comment]
@sta1r - they appear every 5 mins

**Comment by sta1r** [comment]
@dbashyal I'd recommend opening a ticket with our support team to resolve this issue: https://support.dotdigital.com/hc/en-gb/articles/360011229880. You can mention you've opened this Github issue and had some discussion with me already. 

I suspect you have some in-progress imports (see Reports > Importer Status) that are not clearing for some reason, or else there's a problem with your API credentials. 

I'll leave this open for now while we ship the property check.

**Comment by sta1r** [comment]
For anyone else who stumbles across this issue...

If you are in R2 or R3 and have upgraded to 4.18.0 or 4.18.1, you may have a problem with your imports (and with API requests more generally). To resolve, re-save your account credentials - either at default level, or in each website scope where your account settings do not inherit. 

You will also need to manually reset any queued imports since you upgraded. 

We'll have a fix for this in 4.18.2.
